# Sirve para verificar cuantos jugadores debe haber para iniciar.
purga:
  jugadores_maximos: 1

strive-commands:
  - host
  - reload
spleef:
  pos1:
    x1: -7
    y1: 155
    z1: 7
  pos2:
    x2: 7
    y2: 160
    z2: -7
#Coordenadas de la restauración del mapa
  pos3:
    x1: 30
    y1: 0
    z1: 30
  pos4:
    x2: -30
    y2: 200
    z2: -30
  duracionInicio: 11 #No se incluye el último número Ej. Pones 10 pero empieza en 9

