# Sirve para verificar cuantos jugadores debe haber para iniciar.
purga:
  jugadores_maximos: 1

strive-commands:
  - host
  - reload
spleef:
  pos1:
    x1: -7
    y1: 155
    z1: 7
  pos2:
    x2: 7
    y2: 160
    z2: -7
  duracionInicio: 11 #No se incluye el ultimo numero Ej. pones 10 pero empieza en 9