name: Purga
version: '1.0 [BETA]'
main: com.badstudio.plugin.Main
api-version: '1.21'
authors: [ SMyBad, Vantuko1 ]
description: Private Plugin
commands:
  spleef:
    permission: op
  strive:
    permission: op